### ISSUE TITLE
Download phase crashes

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/crmprtd#169]
```
Unhandled exception during 'download'
Traceback (most recent call last):
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download.py", line 62, in main
    download_module = get_download_module(args.network)
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download.py", line 38, in get_download_module
    return import_module(f"crmprtd.networks.{network}.download")
  File "/modules/python/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/networks/bc_hydro/download.py", line 26, in <module>
    from crmprtd.download_utils import verify_date
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download_utils.py", line 10, in <module>
    import requests
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
/bin/sh: -L: command not found
Unhandled exception during 'download - cache - process' pipeline
Traceback (most recent call last):
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download_cache_process.py", line 454, in main
    dispatch(**vars(args))
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download_cache_process.py", line 314, in dispatch
    dispatch_network(network_name=network, **kwargs)
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/download_cache_process.py", line 277, in dispatch_network
    download_and_process(
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/infill.py", line 127, in download_and_process
    chain_subprocesses(
  File "/storage/home/crmprtd/env_4.3.1.dev3/lib/python3.8/site-packages/crmprtd/infill.py", line 44, in chain_subprocesses
    proc = run(
  File "/modules/python/3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'crmprtd_process -N bc_hydro -c postgresql://crmprtd@db.pcic.uvic.ca:5433/crmp?keepalives=1&keepalives_idle=300&keepalives_interval=300&keepalives_count=9 -L ~/logging.yaml --log_filename ~/bc_hydro/logs/crmp_bc_hydro_json.log' returned non-zero exit status 127.
```

I believe the problem is because I did not specify a version constraint for `requests` (the importing module), and got one that is too advanced. We shall see.

**Comment by rod-glover** [comment]
Certainly the pre-Poetry crmprtd pinned `requests` at 2.22, which is from 2019 (!), and without pinning we got 2.28.2, which was the latest version as of Apr 20, 2023, when locking was done. 

The ImportError message points at a 2019 [issue](https://github.com/urllib3/urllib3/issues/2168), which was addressed by a [PR](https://github.com/urllib3/urllib3/pull/2705) closed in Aug 2022. 

This seems pretty suggestive that whatever we are doing is not compatible with the latest version of requests. A quick diagnostic is to revert to 2.22 and test. 

The larger question is why this is a problem. 

Hypothesis: In Python 3.8, only an older `ssl` module, not compatible with the dropped support, is available.

Further info from [Py 3.8 docs for `ssl`](https://docs.python.org/3.8/library/ssl.html):

> Note Some behavior may be platform dependent, since calls are made to the operating system socket APIs. The installed version of OpenSSL may also cause variations in behavior. For example, TLSv1.1 and TLSv1.2 come with openssl version 1.0.1.

**Comment by rod-glover** [comment]
So I think the reasonable, expedient and possibly only fix available is to pin `requests` to 2.22.

**Comment by gopackgo90** [comment]
Followed here from you linking to https://github.com/urllib3/urllib3/issues/2168, the issue isn't technically related to `requests`, but one of `requests`'s dependencies, `urllib3`. Depending on what OS you're using, you could update to a newer version that uses a Python that's compiled with OpenSSL 1.1.1,
https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#ssl-module-is-compiled-with-openssl-1-0-2-k-fips, or if you end up having to pin a dependency, you should pin `urllib3`, not `requests`, see https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#pinning-urllib3-2.

**Comment by jameshiebert** [comment]
Great advice. Thanks @gopackgo90 !

**Comment by rod-glover** [comment]
Thank you for your advice @gopackgo90. A couple of observations, if you have the time or patience to consider them:

`urllib3` ver. 1.26.15 _was_ installed in the failing release. According to https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#pinning-urllib3-2 that version is supposed to sidestep the problem. So I don't think that particular fix is going to work here.

Pinning `requests` to 2.22.0 did work. It's not a nice solution, but for now it is probably the most straightforward.

I suspect that it is at root the Python installation that is the problem. I'm not sure how soon IT can address that.

If you have any further insights , I'd be very interested to hear them.

**Comment by gopackgo90** [comment]
According to this commit, https://github.com/urllib3/urllib3/commit/e5eac0cbfb6920fcc0b6dd584f23eeb14277ab3f#diff-793e73e680de400394dedf7d080fbcef6e74c065ffcc10b8c3dc11217a786e0bR36, the error message you have in your logs was first in `urllib3` 2.0.0, so I doubt it's possible you would have seen that error message in 1.26.15.

**Comment by rod-glover** [comment]
Ach, you are right, I checked the wrong virtualenv. Thank you for your time and care, @gopackgo90 .

**Comment by gopackgo90** [comment]
Happy to help!
