### ISSUE TITLE
moti_hourly.py is broken in Python 3

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#7]
```
(env) [crmprtd@crmprtd ~]$ moti_hourly.py -c 'postgresql://dbuser@dbhost/crmp' --auth=$AUTH_FILE --auth_key=moti -l ~/moti/logs/crmprtd.log --log_level=ERROR -C ~/moti/cache/
Traceback (most recent call last):
  File "/storage/home/crmprtd/env/bin/moti_hourly.py", line 151, in <module>
    main(args)
  File "/storage/home/crmprtd/env/bin/moti_hourly.py", line 92, in main
    f.write(req.content)
TypeError: must be str, not bytes
```

**Comment by jameshiebert** [comment]
Same goes for ``real_time_ec.py``:

```
2017-09-22 10:51:01,221:INFO:crmprtd.ec - Saving data to /home/crmprtd/ec/download/hourly_bc_2017092112_e.xml
Traceback (most recent call last):
  File "/storage/home/crmprtd/env/bin/real_time_ec.py", line 151, in <module>
    main(args)
  File "/storage/home/crmprtd/env/bin/real_time_ec.py", line 73, in main
    f.write(req.content)
TypeError: must be str, not bytes
```
