### ISSUE TITLE
AttributeError in wamr.normalize when running infill_all script

### ISSUE THREAD

**Issue by nannau** [pacificclimate/crmprtd#76]
While running the infill script for the most recent outage, the new version `3.1.3` gives the following error when running `crmprtd_infill_all`:

```
2020-07-17 11:03:36,971:INFO:crmprtd.wamr.normalize - Starting WAMR data normalization
Traceback (most recent call last):
  File "/storage/home/nannau/crmp/crmpvenv/bin/crmprtd_process", line 33, in <module>
    sys.exit(load_entry_point('crmprtd', 'console_scripts', 'crmprtd_process')())
  File "/storage/home/nannau/crmp/crmprtd_3.1.3/crmprtd/crmprtd/process.py", line 91, in main
    process(args.connection_string, args.sample_size, args.network, args.diag)
  File "/storage/home/nannau/crmp/crmprtd_3.1.3/crmprtd/crmprtd/process.py", line 61, in process
    rows = [row for row in norm_mod.normalize(download_iter)]
  File "/storage/home/nannau/crmp/crmprtd_3.1.3/crmprtd/crmprtd/process.py", line 61, in <listcomp>
    rows = [row for row in norm_mod.normalize(download_iter)]
  File "/storage/home/nannau/crmp/crmprtd_3.1.3/crmprtd/crmprtd/wamr/normalize.py", line 27, in normalize
    reader = csv.DictReader(file_stream.getvalue().decode('utf-8')
AttributeError: 'generator' object has no attribute 'getvalue'
/storage/home/nannau/crmp/crmprtd_3.1.3/crmprtd/scripts/infill_all.py:193: UserWarning: WMB cannot be infilled since the period of infilling is outside the currently offered data (the previous day).
  warn(warning_msg['disjoint'].format("WMB", "day"))
```

It was run with the following command:

```
crmprtd_infill_all -S '2020/07/11 05:00:00' -E '2020/07/13 00:00:00' -a auth -c connection_string -L log_config -l logfile -N wamr wmb
```

Might this have something to do with #75?

**Comment by jameshiebert** [comment]
Yep. Drop back to 3.1.2 in the mean time.

**Comment by jameshiebert** [comment]
Should be fixed now.
